export enum SendMobileRequestConflictErrorCode {
  INVALID_NONCE_OR_MOBILE = 'INVALID_NONCE_OR_MOBILE',
  INVALID_FORMAT_MOBILE_OR_COUNTRY_CODE = 'INVALID_FORMAT_MOBILE_OR_COUNTRY_CODE',
  INSUFFICIENT_FUNDS = 'INSUFFICIENT_FUNDS',
  SYSTEM_ERROR = 'SYSTEM_ERROR',
  FREQUENCY_EXCEEDED = 'FREQUENCY_EXCEEDED',
  RETRIES_EXCEEDED = 'RETRIES_EXCEEDED'
}
