export enum UpdateConsumerConflictEnum {
    FEE_GROUP_INVALID = 'FEE_GROUP_INVALID',
    COUNTRY_INVALID = 'COUNTRY_INVALID',
    CONSUMER_VERIFIED = 'CONSUMER_VERIFIED',
    SOURCE_OF_FUNDS_OTHER_MISSING = 'SOURCE_OF_FUNDS_OTHER_MISSING',
    EMAIL_NOT_UNIQUE = 'EMAIL_NOT_UNIQUE',
    MOBILE_OR_COUNTRY_CODE_INVALID = 'MOBILE_OR_COUNTRY_CODE_INVALID',
    COUNTRY_UNSUPPORTED = 'COUNTRY_UNSUPPORTED',
}
