import { z } from 'zod'

export enum IndustryTypeEnum {
    ACCOUNTING = 'ACCOUNTING',
    AUDIT = 'AUDIT',
    FINANCE = 'FINANCE',
    PUBLIC_SECTOR_ADMINISTRATION = 'PUBLIC_SECTOR_ADMINISTRATION',
    ART_ENTERTAINMENT = 'ART_ENTERTAINMENT',
    AUTO_AVIATION = 'AUTO_AVIATION',
    BANKING_LENDING = 'BANKING_LENDING',
    BUSINESS_CONSULTANCY_LEGAL = 'BUSINESS_CONSULTANCY_LEGAL',
    CONSTRUCTION_REPAIR = 'CONSTRUCTION_REPAIR',
    EDUCATION_PROFESSIONAL_SERVICES = 'EDUCATION_PROFESSIONAL_SERVICES',
    INFORMATIONAL_TECHNOLOGIES = 'INFORMATIONAL_TECHNOLOGIES',
    TOBACCO_ALCOHOL = 'TOBACCO_ALCOHOL',
    GAMING_GAMBLING = 'GAMING_GAMBLING',
    MEDICAL_SERVICES = 'MEDICAL_SERVICES',
    MANUFACTURING = 'MANUFACTURING',
    PR_MARKETING = 'PR_MARKETING',
    PRECIOUS_GOODS_JEWELRY = 'PRECIOUS_GOODS_JEWELRY',
    NON_GOVERNMENTAL_ORGANIZATION = 'NON_GOVERNMENTAL_ORGANIZATION',
    INSURANCE_SECURITY = 'INSURANCE_SECURITY',
    RETAIL_WHOLESALE = 'RETAIL_WHOLESALE',
    TRAVEL_TOURISM = 'TRAVEL_TOURISM',
    FREELANCER = 'FREELANCER',
}

const IndustryTypeEnumSchema = z.nativeEnum(IndustryTypeEnum)
type IndustryTypeEnumType = z.infer<typeof IndustryTypeEnumSchema>

export { IndustryTypeEnumSchema, IndustryTypeEnumType }
