export enum KYBErrorCodeEnum {
    KYB_ALREADY_APPROVED = 'KYB_ALREADY_APPROVED',
    KYB_PERMANENTLY_REJECTED = 'KYB_PERMANENTLY_REJECTED',
    KYB_PENDING_REVIEW = 'KYB_PENDING_REVIEW',
    INDUSTRY_MISSING = 'INDUSTRY_MISSING',
    SOURCE_OF_FUNDS_MISSING = 'SOURCE_OF_FUNDS_MISSING',
}
