[tool.commitizen]
name = "cz_conventional_commits"
version = "2.0.0"
tag_format = "$version"
update_changelog_on_bump = true
version_files = [
    "package.json:version",
    "nuxt.config.ts:app_version",
]
changelog_file="CHANGELOG.md"
