export enum IndustryOccupation {
  'ACCOUNTING' = 'Accounting',
  'AUDIT' = 'Audit',
  'FINANCE' = 'Finance',
  'PUBLIC_SECTOR_ADMINISTRATION' = 'Public sector/ Administration',
  'ART_ENTERTAINMENT' = 'Art/Entertainment',
  'AUTO_AVIATION' = 'Auto/Aviation',
  'BANKING_LENDING' = 'Banking/ Lending',
  'BUSINESS_CONSULTANCY_LEGAL' = 'Business/ Consultancy/ Legal',
  'CONSTRUCTION_REPAIR' = 'Construction/ Repair',
  'EDUCATION_PROFESSIONAL_SERVICES' = 'Education/Professional services',
  'INFORMATIONAL_TECHNOLOGIES' = 'Informational technologies',
  'TOBACCO_ALCOHOL' = 'Tobacco/Alcohol',
  'GAMING_GAMBLING' = 'Gaming/Gambling',
  'MEDICAL_SERVICES' = 'Medical Services',
  'MANUFACTURINGPR_MARKETING' = 'ManufacturingPR/Marketing',
  'PRECIOUS_GOODS_JEWELRY' = 'Precious goods/ Jewelry',
  'NON_GOVERNMENTAL_ORGANIZATION' = 'Non-governmental organization',
  'INSURANCE_SECURITY' = 'Insurance/Security',
  'RETAIL_WHOLESALE' = 'Retail/ Wholesale',
  'TRAVEL_TOURISM' = 'Travel/ Tourism',
  'FREELANCER' = 'Freelancer'
}
