export enum IndustryOccupation {
  'ACCOUNTING' = 'ACCOUNTING',
  'AUDIT' = 'AUDIT',
  'FINANCE' = 'FINANCE',
  'PUBLIC_SECTOR_ADMINISTRATION' = 'PUBLIC_SECTOR_ADMINISTRATION',
  'ART_ENTERTAINMENT' = 'ART_ENTERTAINMENT',
  'AUTO_AVIATION' = 'AUTO_AVIATION',
  'BANKING_LENDING' = 'BANKING_LENDING',
  'BUSINESS_CONSULTANCY_LEGAL' = 'BUSINESS_CONSULTANCY_LEGAL',
  'CONSTRUCTION_REPAIR' = 'CONSTRUCTION_REPAIR',
  'EDUCATION_PROFESSIONAL_SERVICES' = 'EDUCATION_PROFESSIONAL_SERVICES',
  'INFORMATIONAL_TECHNOLOGIES' = 'INFORMATIONAL_TECHNOLOGIES',
  'TOBACCO_ALCOHOL' = 'TOBACCO_ALCOHOL',
  'GAMING_GAMBLING' = 'GAMING_GAMBLING',
  'MEDICAL_SERVICES' = 'MEDICAL_SERVICES',
  'PRECIOUS_GOODS_JEWELRY' = 'PRECIOUS_GOODS_JEWELRY',
  'NON_GOVERNMENTAL_ORGANIZATION' = 'NON_GOVERNMENTAL_ORGANIZATION',
  'INSURANCE_SECURITY' = 'INSURANCE_SECURITY',
  'RETAIL_WHOLESALE' = 'RETAIL_WHOLESALE',
  'TRAVEL_TOURISM' = 'TRAVEL_TOURISM',
  'FREELANCER' = 'FREELANCER'
}

export const IndustryOccupationOptions = [
  { text: 'Accounting', value: IndustryOccupation.ACCOUNTING },
  { value: IndustryOccupation.AUDIT, text: 'Audit' },
  { value: IndustryOccupation.FINANCE, text: 'Finance' },
  { value: IndustryOccupation.PUBLIC_SECTOR_ADMINISTRATION, text: 'Public sector/ Administration' },
  { value: IndustryOccupation.ART_ENTERTAINMENT, text: 'Art/Entertainment' },
  { value: IndustryOccupation.AUTO_AVIATION, text: 'Auto/Aviation' },
  { value: IndustryOccupation.BANKING_LENDING, text: 'Banking/ Lending' },
  { value: IndustryOccupation.BUSINESS_CONSULTANCY_LEGAL, text: 'Business/ Consultancy/ Legal' },
  { value: IndustryOccupation.CONSTRUCTION_REPAIR, text: 'Construction/ Repair' },
  { value: IndustryOccupation.EDUCATION_PROFESSIONAL_SERVICES, text: 'Education/Professional services' },
  { value: IndustryOccupation.INFORMATIONAL_TECHNOLOGIES, text: 'Informational technologies' },
  { value: IndustryOccupation.TOBACCO_ALCOHOL, text: 'Tobacco/Alcohol' },
  { value: IndustryOccupation.GAMING_GAMBLING, text: 'Gaming/Gambling' },
  { value: IndustryOccupation.MEDICAL_SERVICES, text: 'Medical Services' },
  { value: IndustryOccupation.PRECIOUS_GOODS_JEWELRY, text: 'Precious goods/ Jewelry' },
  { value: IndustryOccupation.NON_GOVERNMENTAL_ORGANIZATION, text: 'Non-governmental organization' },
  { value: IndustryOccupation.INSURANCE_SECURITY, text: 'Insurance/Security' },
  { value: IndustryOccupation.RETAIL_WHOLESALE, text: 'Retail/ Wholesale' },
  { value: IndustryOccupation.TRAVEL_TOURISM, text: 'Travel/ Tourism' },
  { value: IndustryOccupation.FREELANCER, text: 'Freelancer' }
]
