export enum EnrolOtpConflictEnum {
    CHANNEL_NOT_SUPPORTED = 'CHANNEL_NOT_SUPPORTED',
    CHANNEL_ALREADY_REGISTERED = 'CHANNEL_ALREADY_REGISTERED',
    MOBILE_NUMBER_NOT_AVAILABLE = 'MOBILE_NUMBER_NOT_AVAILABLE',
    MOBILE_NUMBER_INVALID = 'MOBILE_NUMBER_INVALID',
}
