export enum EnrolDevicePushConflictEnum {
  CHANNEL_NOT_SUPPORTED = 'CHANNEL_NOT_SUPPORTED',
  CHANNEL_NOT_READY = 'CHANNEL_NOT_READY',
  CHANNEL_ALREADY_REGISTERED = 'CHANNEL_ALREADY_REGISTERED',
  MOBILE_NUMBER_NOT_AVAILABLE = 'MOBILE_NUMBER_NOT_AVAILABLE',
  CHALLENGE_LIMIT_EXCEEDED = 'CHALLENGE_LIMIT_EXCEEDED'
}
