export enum VerifyEnrolOtpConflictEnum {
    CHANNEL_NOT_SUPPORTED = 'CHANNEL_NOT_SUPPORTED',
    CHANNEL_ALREADY_REGISTERED = 'CHANNEL_ALREADY_REGISTERED',
    VERIFICATION_CODE_EXPIRED = 'VERIFICATION_CODE_EXPIRED',
    VERIFICATION_CODE_INVALID = 'VERIFICATION_CODE_INVALID',
}
