export enum CreatePasswordConflictsEnum {
    UNRESOLVED_IDENTITY = 'UNRESOLVED_IDENTITY',
    PASSWORD_PROFILE_NOT_CONFIGURED_FOR_CREDENTIAL_TYPE = 'PASSWORD_PROFILE_NOT_CONFIGURED_FOR_CREDENTIAL_TYPE',
    PASSWORD_TOO_SHORT = 'PASSWORD_TOO_SHORT',
    PASSWORD_TOO_LONG = 'PASSWORD_TOO_LONG',
    PASSWORD_TOO_SIMPLE = 'PASSWORD_TOO_SIMPLE',
    PASSWORD_KEY_ALREADY_IN_USE = 'PASSWORD_KEY_ALREADY_IN_USE',
    PASSWORD_ALREADY_CREATED = 'PASSWORD_ALREADY_CREATED',
}
