export enum IssueNotificationConflictEnum {
  STATE_INVALID = 'STATE_INVALID',
  CHANNEL_NOT_SUPPORTED = 'CHANNEL_NOT_SUPPORTED',
  CHANNEL_NOT_REGISTERED = 'CHANNEL_NOT_REGISTERED',
  CHALLENGE_LIMIT_EXCEEDED = 'CHALLENGE_LIMIT_EXCEEDED'
}
