export enum VerifyTokenConflictsEnum {
  STATE_INVALID = 'STATE_INVALID',
  VERIFICATION_CODE_EXPIRED = 'VERIFICATION_CODE_EXPIRED',
  VERIFICATION_CODE_INVALID = 'VERIFICATION_CODE_INVALID',
  CHANNEL_NOT_SUPPORTED = 'CHANNEL_NOT_SUPPORTED',
  CHANNEL_NOT_REGISTERED = 'CHANNEL_NOT_REGISTERED'
}
