export enum CompanyTypeEnum {
  SOLE_TRADER = 'SOLE_TRADER',
  LLC = 'LLC',
  PUBLIC_LIMITED_COMPANY = 'PUBLIC_LIMITED_COMPANY',
  LIMITED_LIABILITY_PARTNERSHIP = 'LIMITED_LIABILITY_PARTNERSHIP',
  NON_PROFIT_ORGANISATION = 'NON_PROFIT_ORGANISATION'
}
