export enum KYCErrorCodeEnum {
  KYC_PENDING_REVIEW = 'KYC_PENDING_REVIEW',
  KYC_REJECTED = 'KYC_REJECTED',
  KYC_ALREADY_APPROVED = 'KYC_ALREADY_APPROVED',
  KYC_LEVEL_NOT_ALLOWED = 'KYC_LEVEL_NOT_ALLOWED',
}
