name: Deploy Reusable Template

inputs:
  cloudfront_id:
    required: true
    type: string
  s3_bucket:
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Setup AWS CLI
      id: install-aws-cli
      uses: unfor19/install-aws-cli-action@master
    - run: |
        cd dist
        aws s3 cp . s3://${{ inputs.s3_bucket }} --recursive
        aws cloudfront create-invalidation --distribution-id ${{ inputs.cloudfront_id }} --paths '/*'
      shell: bash