export enum CreateIdentityConflictsEnum {
  PAYMENT_MODEL_CONSTRAINTS_VIOLATED = 'PAYMENT_MODEL_CONSTRAINTS_VIOLATED',
  PROFILE_NOT_FOUND = 'PROFILE_NOT_FOUND',
  PROFILE_INACTIVE = 'PROFILE_INACTIVE',
  ROOT_EMAIL_NOT_UNIQUE = 'ROOT_EMAIL_NOT_UNIQUE',
  CURRENCY_UNSUPPORTED = 'CURRENCY_UNSUPPORTED',
  SOURCE_OF_FUNDS_OTHER_MISSING = 'SOURCE_OF_FUNDS_OTHER_MISSING',
  FEE_GROUP_INVALID = 'FEE_GROUP_INVALID',
  COUNTRY_INVALID = 'COUNTRY_INVALID',
  TERMS_NOT_ACCEPTED = 'TERMS_NOT_ACCEPTED',
  MOBILE_OR_COUNTRY_CODE_INVALID = 'MOBILE_OR_COUNTRY_CODE_INVALID',
  COUNTRY_UNSUPPORTED = 'COUNTRY_UNSUPPORTED'
}
