export enum UpdateCorporateConflictEnum {
    FEE_GROUP_INVALID = 'FEE_GROUP_INVALID',
    COUNTRY_INVALID = 'COUNTRY_INVALID',
    EMAIL_NOT_UNIQUE = 'EMAIL_NOT_UNIQUE',
    MOBILE_NOT_UNIQUE = 'MOBILE_NOT_UNIQUE',
    ROOT_USER_ALREADY_VERIFIED = 'ROOT_USER_ALREADY_VERIFIED',
    SOURCE_OF_FUNDS_OTHER_MISSING = 'SOURCE_OF_FUNDS_OTHER_MISSING',
    COUNTRY_UNSUPPORTED = 'COUNTRY_UNSUPPORTED',
}
