name: Deploy Demo

on:
  push:
    branches:
      - master

permissions:
  id-token: write
  contents: read

jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Build
        uses: ./.github/templates/build
        with:
          base_url_script: ${{ secrets.DEMO_BASE_URL_SCRIPT }}
          base_url: ${{ secrets.DEMO_BASE_URL }}
          multi_base_url: ${{ secrets.DEMO_BASE_URL }}
          application_id: ${{ secrets.DEMO_PROGRAMME_ID }}
          ui_key: ${{ secrets.DEMO_UI_KEY }}
          environment: ${{ secrets.DEMO_ENVIRONMENT }}
          corporates_profile_id: ${{ secrets.DEMO_CORPORATES_PROFILE_ID }}
          transfers_profile_id: ${{ secrets.DEMO_TRANSFERS_PROFILE_ID }}
          segment_write_key: ${{ secrets.DEMO_SEGMENT_WRITE_KEY }}
          consumers_profile_id: ${{ secrets.DEMO_CONSUMERS_PROFILE_ID }}
          managed_accounts_consumers_profile_id: ${{ secrets.DEMO_MANAGED_ACCOUNTS_CONSUMERS_PROFILE_ID }}
          managed_accounts_corporates_profile_id: ${{ secrets.DEMO_MANAGED_ACCOUNTS_CORPORATES_PROFILE_ID }}
          managed_cards_consumers_profile_id: ${{ secrets.DEMO_MANAGED_CARDS_CONSUMERS_PROFILE_ID }}
          managed_cards_corporates_profile_id: ${{ secrets.DEMO_MANAGED_CARDS_CORPORATES_PROFILE_ID }}
          managed_cards_corporates_profile_id_puk: ${{ secrets.DEMO_MANAGED_CARDS_CORPORATES_PROFILE_ID_PUK }}
          managed_cards_consumers_profile_id_puk: ${{ secrets.DEMO_MANAGED_CARDS_CONSUMERS_PROFILE_ID_PUK }}
          managed_accounts_consumers_profile_id_puk: ${{ secrets.DEMO_MANAGED_ACCOUNTS_CONSUMERS_PROFILE_ID_PUK }}
          managed_accounts_corporates_profile_id_puk: ${{ secrets.DEMO_MANAGED_ACCOUNTS_CORPORATES_PROFILE_ID_PUK }}
          pml_identity_id: ${{ secrets.DEMO_PML_IDENTITY_ID }}
          pml_managed_account_id: ${{ secrets.DEMO_PML_MANAGED_ACCOUNT_ID }}
          recaptcha: ${{ secrets.DEMO_RECAPTCHA }}
      - uses: pietrobolcato/install-azure-cli-action@v1
      - name: Login
        uses: azure/login@v3
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
      - name: Docker Login
        run: az acr login --name ${{ secrets.REGISTRY }}
      - name: Build and Push Docker Image
        run: |
          docker buildx build . --push --platform linux/amd64 --tag ${{ secrets.REGISTRY }}.azurecr.io/onvirtual-cards-app:${{ env.DOCKER_TAG }}