name: Deploy Develop

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ vars.AWS_REGION }}
    steps:
      - name: Checkout 
        uses: actions/checkout@v3
      - name: Build
        uses: ./.github/templates/build
        with:
          base_url_script: ${{ secrets.DEVELOP_BASE_URL_SCRIPT }}
          base_url: ${{ secrets.DEVELOP_BASE_URL }}
          multi_base_url: ${{ secrets.DEVELOP_BASE_URL }}
          application_id: ${{ secrets.DEVELOP_PROGRAMME_ID }}
          ui_key: ${{ secrets.DEVELOP_UI_KEY }}
          environment: ${{ secrets.DEVELOP_ENVIRONMENT }}
          corporates_profile_id: ${{ secrets.DEVELOP_CORPORATES_PROFILE_ID }}
          transfers_profile_id: ${{ secrets.DEVELOP_TRANSFERS_PROFILE_ID }}
          segment_write_key: ${{ secrets.DEVELOP_SEGMENT_WRITE_KEY }}
          consumers_profile_id: ${{ secrets.DEVELOP_CONSUMERS_PROFILE_ID }}
          managed_accounts_consumers_profile_id: ${{ secrets.DEVELOP_MANAGED_ACCOUNTS_CONSUMERS_PROFILE_ID }}
          managed_accounts_corporates_profile_id: ${{ secrets.DEVELOP_MANAGED_ACCOUNTS_CORPORATES_PROFILE_ID }}
          managed_cards_consumers_profile_id: ${{ secrets.DEVELOP_MANAGED_CARDS_CONSUMERS_PROFILE_ID }}
          managed_cards_corporates_profile_id: ${{ secrets.DEVELOP_MANAGED_CARDS_CORPORATES_PROFILE_ID }}
          recaptcha: ${{ secrets.DEVELOP_RECAPTCHA }}
      - name: Deploy
        uses: ./.github/templates/deploy
        with:
          cloudfront_id: ${{ secrets.DEVELOP_CLOUDFRONT_ID }}
          s3_bucket: ${{ secrets.DEVELOP_S3_BUCKET }}